on:
  push:
    branches:
      - '*'

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -lahr
      - run: docker images
      - run: docker build -t gha:da --target=artifact 
      - run: docker images
      - run: whoami 
      - run: docker create --name klorel gha:da
      - run: docker cp klorel:/dist/alfalfa .
      - run: ls -lahr
      - run:  ls -lahr $(pwd)